# Generated by Django 5.2.4 on 2025-07-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for SEO and accessibility', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='noindex',
            field=models.BooleanField(default=False),
        ),
    ]
