# Generated by Django 5.2.4 on 2025-07-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_published_date_post_featured_image_alt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='noindex',
        ),
    ]
