# Generated by Django 5.2.4 on 2025-07-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='noindex',
            field=models.BooleanField(default=False),
        ),
    ]
