# Generated by Django 5.2.4 on 2025-07-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
