# Generated by Django 5.2.4 on 2025-07-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0002_influencer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='type',
            field=models.CharField(choices=[('NANO', 'Nano (1k-10k followers)'), ('MICRO', 'Micro (10k-100k followers)'), ('MACRO', 'Macro (100k-1M followers)'), ('MEGA', 'Mega (1M+ followers)'), ('CELEB', 'Celebrity (Public figure with large following)')], default='MICRO', help_text='Category based on follower count or influence level', max_length=10),
        ),
    ]
