# Generated by Django 5.2.4 on 2025-08-14 12:59

import django.db.models.deletion
import influencer.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0003_alter_influencer_slug_alter_influencer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='influencer',
        ),
        migrations.RemoveField(
            model_name='suggestedinfluenceredit',
            name='influencer',
        ),
        migrations.RemoveField(
            model_name='suggestedinfluenceredit',
            name='suggested_by',
        ),
        migrations.AlterModelOptions(
            name='influencer',
            options={},
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='blog_content',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='collaborations_count',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='posts_count',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='tiktok_url',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='type',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='views_count',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='influencer',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='assets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='biography',
            field=models.TextField(blank=True, help_text='Detailed life & career history', null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='brand_collaborations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='businesses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='controversies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='estimated_net_worth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='eye_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='hair_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='instagram_followers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='media_appearances',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='poster_pic',
            field=models.ImageField(blank=True, null=True, upload_to=influencer.models.poster_pic_upload_path),
        ),
        migrations.AddField(
            model_name='influencer',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=influencer.models.profile_pic_upload_path),
        ),
        migrations.AddField(
            model_name='influencer',
            name='profile_summary',
            field=models.TextField(blank=True, help_text='Short, inspiring overview of the influencer', null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='public_perception',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='tiktok_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='youtube_channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='InfluencerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Direct Instagram image link')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='influencer.influencer')),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_url', models.URLField(help_text='Full Twitter/X post link')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='influencer.influencer')),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram Reels')], max_length=20)),
                ('video_url', models.URLField(help_text='YouTube or Instagram video link')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='influencer.influencer')),
            ],
        ),
        migrations.DeleteModel(
            name='Collaboration',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='SuggestedInfluencerEdit',
        ),
    ]
