# Generated by Django 5.2.4 on 2025-08-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0004_remove_content_influencer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='age',
        ),
        migrations.AddField(
            model_name='influencer',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Select categories this influencer specializes in.', related_name='influencers', to='influencer.category'),
        ),
    ]
