# Generated by Django 5.2.4 on 2025-08-20 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0006_influencercommunitypost_postnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencercommunitypost',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
