# Generated by Django 5.2.4 on 2025-08-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0007_alter_influencercommunitypost_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='influencercommunitypost',
            options={'ordering': ['-updated_at']},
        ),
    ]
